version: '3'

services:
  node-app:
    container_name: node-app
    build: .
    image: node-app
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
  
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 3307:3307
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge